### ISSUE TITLE
domain level filtering possible issue

### ISSUE THREAD

**Issue by nc88keyz** [kabadisha/host-based-vpn-routing#1]
when adding the domains does it do filtering such as *.bamgrid.com or do you have to put analytics.clients.bamgrid.com in the rules file?  Great script btw. Love the flexibility for my Merlin powered Asus router.?

Sorry not a question. Hopefully you will give an answer and I am not bothering you too much.

**Comment by kabadisha** [comment]
Currently, the script doesn't support wildcards.
It uses nslookup command to fetch the IPs and that command doesn't support wildcards.
I don't think there is a simple way to do it, but please do let me know if you can think of one.
